version: "3.3"
services:
  server:
    image: dariusbalanica/photo-gear-store:latest-server
    links:
      - db
    depends_on:
      - db
    ports:
      - "5000:5000"
    tty: true
    stdin_open: true

  client:
    image: dariusbalanica/photo-gear-store:latest-client
    links:
      - server
    depends_on:
      - db
    tty: true
    stdin_open: true

  administration:
    image: dariusbalanica/photo-gear-store:latest-administration
    links:
      - db
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - db
    ports:
      - "3000:3000"
    user: '0'
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
    db_data: {}
    grafana_data: {}
