version: "2"
services:
  server:
    image: dariusbalanica/photo-gear-store:latest-server
    links:
      - db
    depends_on:
      - db
    ports:
      - "5000:5000"
    tty: true
    stdin_open: true
    networks:
      - my_network

  client:
    image: dariusbalanica/photo-gear-store:latest-client
    links:
      - server
    depends_on:
      - db
    tty: true
    stdin_open: true
    networks:
      - my_network

  administration:
    image: dariusbalanica/photo-gear-store:latest-administration
    links:
      - db
    depends_on:
      - db
    tty: true
    stdin_open: true
    networks:
      - my_network

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      - my_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - db
    ports:
      - "3000:3000"
    user: '0'
    volumes:
      - /srv/docker/grafana/data:/var/lib/grafana
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
